Fix test-sanity-docker failures
ansible-collections/vyos.vyos pull request #124
Opened 2021-02-16 14:34 UTC by GomathiselviS

Signed-off-by: GomathiselviS <gomathiselvi@gmail.com>

##### SUMMARY

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2021-02-17 13:45 UTC, Qalthos requested changes
This seems to be the issue

2021-02-17 13:45 UTC, Qalthos commented on plugins/module_utils/network/vyos/config/ospf_interfaces/ospf_interfaces.py
> +        wanted = {}
```suggestion
        wantd = {}
```

2021-02-18 16:13 UTC, justjais approved these changes

2021-02-18 17:34 UTC, Qalthos reviewed
Looks good, but it seems odd that we're keeping up some 2.6 compatibility but still skipping the check

2021-02-18 17:34 UTC, Qalthos commented on tests/sanity/ignore-2.10.txt
> +plugins/module_utils/network/vyos/config/ospf_interfaces/ospf_interfaces.py compile-2.6!skip
What's the issue in this file? Are there other dict comprehensions that didn't get fixed?

2021-02-18 20:26 UTC, merged