Vyos route maps
ansible-collections/vyos.vyos pull request #156
Opened 2021-05-05 11:04 UTC by ashwini-mhatre

##### SUMMARY

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

vyos_route_maps

##### ADDITIONAL INFORMATION

```paste below

```

2021-05-06 14:00 UTC, GomathiselviS requested changes

2021-05-06 15:22 UTC, ashwini-mhatre commented on tests/integration/test-inventory
> +iosxr-7.0.2  ansible_port=22 ansible_host=127.0.0.1 ansible_user=vagrant
added by mistake

2021-05-06 15:23 UTC, ashwini-mhatre commented on plugins/modules/vyos_route_maps.py
> +EXAMPLES = """
ack

2021-05-06 15:25 UTC, ashwini-mhatre commented on plugins/module_utils/network/vyos/config/route_maps/route_maps.py
> +        self._compare_entries(want=w_entries, have=h_entries)
outside entries we only have route_map key . and we only remove route_map when  performing delete and overridden operation which is taken cared through 125 to 135 code

2021-05-06 15:27 UTC, ashwini-mhatre commented on plugins/module_utils/network/vyos/config/route_maps/route_maps.py
> +
this is taken care in compare method as vyos has linear structure we dont need to handle have entries. please check examples for more details

2021-05-06 15:27 UTC, ashwini-mhatre commented on plugins/module_utils/network/vyos/rm_templates/route_maps.py
> +            "remval": "policy route-map {{route_map}}",
ack

2021-05-06 15:27 UTC, ashwini-mhatre commented on plugins/module_utils/network/vyos/argspec/route_maps/route_maps.py
> +                        "continue": {"type": "int"},
ack

2021-05-07 13:29 UTC, ashwini-mhatre commented on plugins/module_utils/network/vyos/argspec/route_maps/route_maps.py
> +                        "rule_number": {"type": "int"},
ack

2021-05-07 13:30 UTC, ashwini-mhatre commented on tests/integration/network-integration.cfg
> +interpreter_python=/Users/amhatre/ansible_venvs/py3.6.10/bin/python
removed

2021-05-10 09:58 UTC, NilashishC commented on plugins/modules/vyos_route_maps.py
> +version_added: 2.0.2
This should be the next minor version.

2021-05-10 15:23 UTC, ashwini-mhatre commented
recheck

2021-05-11 15:22 UTC, GomathiselviS approved these changes

2021-05-11 18:34 UTC, merged