Update l3_interfaces.py - Fix for issue 295
ansible-collections/vyos.vyos pull request #314
Opened 2023-04-13 09:10 UTC by Charlie-Root

Fix for issue:
https://github.com/ansible-collections/vyos.vyos/issues/295

##### SUMMARY

Fix for l3_interfaces facts when address set to no-default-link-local 

Fix for issue: https://github.com/ansible-collections/vyos.vyos/issues/295

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

vyos_l3_interfaces
##### ADDITIONAL INFORMATION

```paste below

```

2023-04-19 13:10 UTC, Qalthos commented
Can you please add a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-changelog-fragments) to your PR? Thanks!

2023-04-19 14:26 UTC, Qalthos requested changes
Can you please add a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-changelog-fragments) to your PR? Thanks!

2023-04-26 06:47 UTC, Charlie-Root commented
> Can you please add a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-changelog-fragments) to your PR? Thanks!

Done.

2023-04-28 16:20 UTC, Qalthos requested changes

2023-04-28 16:20 UTC, Qalthos commented on changelogs/fragments/l3_interfaces.yaml
> +  - vyos-l3_interface_facts - fixed #295 - error when using no-default-link-local option.
```suggestion
bugfixes:
  - vyos-l3_interface_facts - fixed error when using no-default-link-local option. (https://github.com/ansible-collections/vyos.vyos/issues/295)
```

2023-05-01 18:35 UTC, merged