Facts nw interfaces
ansible-collections/vyos.vyos pull request #318
Opened 2023-04-26 07:04 UTC by Charlie-Root

##### SUMMARY
Add support for Bridge, Tunnel and Dummy interfaces as mentioned in #265 

##### ISSUE TYPE
- Bugfix Pull Request

2023-04-28 16:17 UTC, Qalthos requested changes

2023-04-28 16:17 UTC, Qalthos commented on changelogs/fragments/l3_interfaces.yaml
> +  - vyos-l3_interface_facts - Add support for Tunnel, Bridge and Dummy interfaces
```suggestion
minor_changes:
  - vyos-l3_interface_facts - Add support for Tunnel, Bridge and Dummy interfaces. (https://github.com/ansible-collections/vyos.vyos/issues/265)
```

2023-05-01 18:37 UTC, Qalthos requested changes

2023-05-01 18:37 UTC, Qalthos commented on changelogs/fragments/l3_interfaces.yaml
This should have a different name than the one in the other PR

2023-05-10 04:47 UTC, Charlie-Root commented on changelogs/fragments/l3_interfaces.yaml
Done

2023-05-15 13:59 UTC, Qalthos approved these changes

2023-05-19 13:58 UTC, merged